-- 订单基础表：仅保存交易、支付、充值、退款及商品订单事实，不包含账户余额或第三方支付 SDK。
-- 新业务 ID 使用 ascii_bin；充值档位 sku_id 沿用 VARCHAR(64) utf8mb4_general_ci，user_id 沿用 VARCHAR(255) utf8mb4_general_ci。
-- 要求 MySQL 8.0.16+ 实际执行 CHECK；连接 session time_zone 必须为 +00:00，应用传入时间也必须为 UTC。
-- 不使用外键或分区。跨表用户、币种、总额及状态由后续短事务校验；本迁移不实现支付/入账。
-- 用户列表按 (created_at,id) 游标且 limit <=100；超时任务按 (status,expire_at,id) 分批且每批 <=100。
-- 商品目录是非充值商品下单快照的来源；refund_order 是独立退款事实，不覆写原支付事实。

CREATE TABLE `product` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `product_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '商品业务标识，供订单明细引用',
    `product_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '商品类型，例如 MEMBERSHIP 或 PHYSICAL_PRODUCT',
    `title` VARCHAR(256) NOT NULL COMMENT '商品名称快照来源，最多256个字符',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '商品标价币种，支持 CNY 与 MLC_COIN；单个商品不混用币种',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '商品状态：0停用，1启用，2归档',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_product_id` (`product_id`),
    KEY `idx_product_status_id` (`status`, `id` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='商品基础目录，不承担库存或支付';

CREATE TABLE `product_sku` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `sku_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '商品 SKU 业务标识',
    `product_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属商品业务标识，不建立外键',
    `sku_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SKU 唯一业务编码',
    `title` VARCHAR(256) NOT NULL COMMENT 'SKU 展示名称，订单创建时应复制为快照',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SKU 定价币种，支持 CNY 与 MLC_COIN；不支持单 SKU 混合币种',
    `amount` BIGINT NOT NULL COMMENT 'SKU 单价，整数最小单位，不得为负',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT 'SKU 状态：0停用，1启用，2归档',
    `version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'SKU 乐观锁版本号，从1开始',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_sku_id` (`sku_id`),
    UNIQUE KEY `uk_product_sku_code` (`sku_code`),
    KEY `idx_product_sku_product_status_id` (`product_id`, `status`, `id` DESC),
    CONSTRAINT `ck_product_sku_amount_nonnegative` CHECK (`amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='商品 SKU 基础目录';

CREATE TABLE `trade_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键，用于稳定游标分页',
    `trade_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '交易订单业务标识，对外使用',
    `user_id` VARCHAR(255) NOT NULL COMMENT '下单用户业务标识，兼容 users.user_id',
    `request_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建请求幂等标识，与 user_id 联合唯一',
    `request_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建请求规范化内容 SHA-256；同 request_id 重试时必须一致',
    `order_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '订单类型：RECHARGE、MEMBERSHIP、PRODUCT',
    `title` VARCHAR(256) NOT NULL COMMENT '下单时订单标题快照',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '订单币种，支持 CNY 与 MLC_COIN；一单不混用币种',
    `total_amount` BIGINT NOT NULL COMMENT '商品总金额，整数最小单位，不得为负',
    `discount_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '优惠金额，整数最小单位，不得为负',
    `payable_amount` BIGINT NOT NULL COMMENT '应付金额，整数最小单位，不得为负；必须等于总额减优惠',
    `trade_status` TINYINT NOT NULL DEFAULT 0 COMMENT '交易状态：0CREATED，1PENDING_PAYMENT，2PAID，3PROCESSING，4COMPLETED，5CANCELLED，6REFUNDING，7REFUNDED',
    `source` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '订单来源，例如 APP、WEB；可为空',
    `expire_at` DATETIME(3) DEFAULT NULL COMMENT '订单支付截止时间，UTC，精确到毫秒；可为空',
    `paid_at` DATETIME(3) DEFAULT NULL COMMENT '支付完成时间，UTC，精确到毫秒；未支付为空',
    `completed_at` DATETIME(3) DEFAULT NULL COMMENT '交易完成时间，UTC，精确到毫秒；未完成为空',
    `cancelled_at` DATETIME(3) DEFAULT NULL COMMENT '取消时间，UTC，精确到毫秒；未取消为空',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_trade_order_id` (`trade_order_id`),
    UNIQUE KEY `uk_trade_order_request_user` (`user_id`, `request_id`),
    KEY `idx_trade_order_user_created_id` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_trade_order_status_expire_id` (`trade_status`, `expire_at`, `id`),
    CONSTRAINT `ck_trade_order_total_amount_nonnegative` CHECK (`total_amount` >= 0),
    CONSTRAINT `ck_trade_order_discount_amount_nonnegative` CHECK (`discount_amount` >= 0),
    CONSTRAINT `ck_trade_order_payable_amount_nonnegative` CHECK (`payable_amount` >= 0),
    CONSTRAINT `ck_trade_order_amount_equation` CHECK (CAST(`total_amount` AS DECIMAL(30,0)) - CAST(`discount_amount` AS DECIMAL(30,0)) = CAST(`payable_amount` AS DECIMAL(30,0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='统一交易订单事实';

CREATE TABLE `trade_order_item` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `order_item_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '订单明细业务标识',
    `trade_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属交易订单业务标识，不建立外键',
    `line_no` SMALLINT UNSIGNED NOT NULL COMMENT '订单内行号1至100，联合唯一约束使每单最多100行；创建时必须同事务写齐',
    `user_id` VARCHAR(255) NOT NULL COMMENT '下单用户业务标识，兼容 users.user_id',
    `product_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '商品业务标识快照',
    `sku_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SKU 业务标识快照',
    `product_title` VARCHAR(256) NOT NULL COMMENT '商品名称快照',
    `sku_title` VARCHAR(256) DEFAULT NULL COMMENT 'SKU 名称快照，可为空',
    `quantity` INT UNSIGNED NOT NULL COMMENT '购买数量，必须大于0；单明细数量有界',
    `unit_amount` BIGINT NOT NULL COMMENT '明细单价，整数最小单位，不得为负',
    `total_amount` BIGINT NOT NULL COMMENT '明细总金额，整数最小单位，必须等于单价乘数量',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_trade_order_item_id` (`order_item_id`),
    UNIQUE KEY `uk_trade_order_item_line` (`trade_order_id`, `line_no`),
    KEY `idx_trade_order_item_user_created_id` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_trade_order_item_product_id` (`product_id`, `id`),
    CONSTRAINT `ck_trade_order_item_quantity_bounded` CHECK (`quantity` > 0 AND `quantity` <= 100000),
    CONSTRAINT `ck_trade_order_item_line_bounded` CHECK (`line_no` BETWEEN 1 AND 100),
    CONSTRAINT `ck_trade_order_item_unit_amount_nonnegative` CHECK (`unit_amount` >= 0),
    CONSTRAINT `ck_trade_order_item_total_amount_nonnegative` CHECK (`total_amount` >= 0),
    CONSTRAINT `ck_trade_order_item_amount_no_overflow` CHECK (CAST(`total_amount` AS DECIMAL(30,0)) = CAST(`unit_amount` AS DECIMAL(30,0)) * `quantity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='交易订单明细，数量上限用于防止异常放大';

CREATE TABLE `payment_recharge_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `recharge_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '充值订单业务标识',
    `trade_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '关联交易订单业务标识，不建立外键',
    `user_id` VARCHAR(255) NOT NULL COMMENT '充值用户业务标识，兼容 users.user_id',
    `request_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建请求幂等标识，与 user_id 联合唯一',
    `request_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建请求规范化内容 SHA-256；冲突时不得复用旧订单',
    `sku_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '充值档位业务标识快照，类型及排序规则兼容 payment_recharge_sku.sku_id',
    `sku_snapshot_title` VARCHAR(128) NOT NULL COMMENT '充值档位标题快照',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '充值支付币种仅允许 CNY，禁止使用平台币自充',
    `pay_amount` BIGINT NOT NULL COMMENT '实际支付人民币金额，单位分，不得为负',
    `coin_amount` BIGINT NOT NULL COMMENT '基础平台币数量，不得为负',
    `bonus_coin` BIGINT NOT NULL DEFAULT 0 COMMENT '赠送平台币数量，不得为负',
    `total_coin` BIGINT NOT NULL COMMENT '平台币总数量，必须等于基础币加赠币',
    `order_status` TINYINT NOT NULL DEFAULT 0 COMMENT '充值订单状态：0CREATED，1PENDING_PAYMENT，2PAID，3COMPLETED，4CANCELLED，5REFUNDING，6REFUNDED',
    `payment_status` TINYINT NOT NULL DEFAULT 0 COMMENT '充值支付状态：0INIT，1PENDING，2SUCCESS，3FAILED，4CLOSED',
    `expire_at` DATETIME(3) NOT NULL COMMENT '支付截止时间，UTC，精确到毫秒',
    `paid_at` DATETIME(3) DEFAULT NULL COMMENT '支付完成时间，UTC，精确到毫秒；未支付为空',
    `completed_at` DATETIME(3) DEFAULT NULL COMMENT '充值完成时间，UTC，精确到毫秒；未完成为空',
    `cancelled_at` DATETIME(3) DEFAULT NULL COMMENT '取消时间，UTC，精确到毫秒；未取消为空',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_recharge_order_id` (`recharge_order_id`),
    UNIQUE KEY `uk_payment_recharge_order_request_user` (`user_id`, `request_id`),
    UNIQUE KEY `uk_payment_recharge_order_trade_id` (`trade_order_id`),
    KEY `idx_payment_recharge_order_user_created_id` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_payment_recharge_order_status_expire_id` (`order_status`, `expire_at`, `id`),
    CONSTRAINT `ck_payment_recharge_order_currency` CHECK (`currency` = 'CNY'),
    CONSTRAINT `ck_payment_recharge_order_pay_amount_nonnegative` CHECK (`pay_amount` >= 0),
    CONSTRAINT `ck_payment_recharge_order_coin_amount_nonnegative` CHECK (`coin_amount` >= 0),
    CONSTRAINT `ck_payment_recharge_order_bonus_coin_nonnegative` CHECK (`bonus_coin` >= 0),
    CONSTRAINT `ck_payment_recharge_order_total_coin_nonnegative` CHECK (`total_coin` >= 0),
    CONSTRAINT `ck_payment_recharge_order_coin_equation` CHECK (CAST(`total_coin` AS DECIMAL(30,0)) = CAST(`coin_amount` AS DECIMAL(30,0)) + CAST(`bonus_coin` AS DECIMAL(30,0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='充值订单事实，关联统一交易订单';

CREATE TABLE `payment_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `payment_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '支付尝试业务标识，每次重复支付尝试可新建',
    `trade_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '关联交易订单业务标识，不建立外键',
    `user_id` VARCHAR(255) NOT NULL COMMENT '支付用户业务标识，兼容 users.user_id',
    `request_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '支付尝试请求幂等标识，与用户联合唯一；新尝试使用新请求标识',
    `request_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化支付请求 SHA-256；重放必须比较哈希，不同内容返回冲突',
    `payment_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '支付方式，例如 COIN；本基础表不实现第三方 SDK',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '支付币种，支持 CNY 与 MLC_COIN；单个支付尝试不混用币种',
    `amount` BIGINT NOT NULL COMMENT '支付金额，整数最小单位，不得为负',
    `payment_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态：0INIT，1PENDING，2SUCCESS，3FAILED，4CLOSED',
    `client_type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '发起支付的客户端类型，可为空',
    `merchant_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '外部商户业务标识，可为空',
    `channel` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '外部支付渠道标识，可为空',
    `external_payment_id` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '外部支付单号，可为空；同商户同渠道下唯一',
    `expire_at` DATETIME(3) NOT NULL COMMENT '支付尝试截止时间，UTC，精确到毫秒',
    `paid_at` DATETIME(3) DEFAULT NULL COMMENT '支付成功时间，UTC，精确到毫秒；未成功为空',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_order_payment_id` (`payment_id`),
    UNIQUE KEY `uk_payment_order_request_user` (`user_id`, `request_id`),
    UNIQUE KEY `uk_payment_order_external` (`merchant_id`, `channel`, `external_payment_id`),
    KEY `idx_payment_order_trade_id` (`trade_order_id`, `id`),
    KEY `idx_payment_order_user_created_id` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_payment_order_status_expire_id` (`payment_status`, `expire_at`, `id`),
    CONSTRAINT `ck_payment_order_amount_nonnegative` CHECK (`amount` >= 0),
    CONSTRAINT `ck_payment_order_external_scope` CHECK (`external_payment_id` IS NULL OR (`external_payment_id` <> '' AND `merchant_id` IS NOT NULL AND `merchant_id` <> '' AND `channel` IS NOT NULL AND `channel` <> ''))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='支付尝试事实，不代表已接入外部支付渠道';

CREATE TABLE `refund_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据库内部自增主键',
    `refund_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款订单业务标识',
    `trade_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原交易订单业务标识，不建立外键',
    `payment_order_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '原支付单业务标识，可为空',
    `user_id` VARCHAR(255) NOT NULL COMMENT '退款用户业务标识，兼容 users.user_id',
    `request_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款请求幂等标识，与 user_id 联合唯一',
    `request_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款请求规范化内容 SHA-256；冲突时不得复用旧退款单',
    `currency` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款币种，支持 CNY 与 MLC_COIN；单笔退款不混用币种',
    `amount` BIGINT NOT NULL COMMENT '退款金额，整数最小单位，不得为负',
    `refund_status` TINYINT NOT NULL DEFAULT 0 COMMENT '退款状态：0INIT，1PROCESSING，2SUCCESS，3FAILED，4CLOSED',
    `reason` VARCHAR(256) DEFAULT NULL COMMENT '退款原因，可为空',
    `expire_at` DATETIME(3) DEFAULT NULL COMMENT '退款处理截止时间，UTC，精确到毫秒；可为空',
    `completed_at` DATETIME(3) DEFAULT NULL COMMENT '退款完成时间，UTC，精确到毫秒；未完成为空',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC，精确到毫秒',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC，精确到毫秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_refund_order_id` (`refund_order_id`),
    UNIQUE KEY `uk_refund_order_request_user` (`user_id`, `request_id`),
    KEY `idx_refund_order_trade_id` (`trade_order_id`, `id`),
    KEY `idx_refund_order_user_created_id` (`user_id`, `created_at` DESC, `id` DESC),
    KEY `idx_refund_order_status_expire_id` (`refund_status`, `expire_at`, `id`),
    CONSTRAINT `ck_refund_order_amount_nonnegative` CHECK (`amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='退款订单事实，仅记录退款申请与状态';
