# 执行：
# 清理容器：  docker-compose -f config/docker/hg_docker_compose.dev.yml down
# 重新构建并启动：  docker-compose -f config/docker/hg_docker_compose.dev.yml up --build
version: "3.9"

services:
  mysql:
    image: mysql:8.0
    # container_name: docker-mysql-mlc_go # 可选，但需和实际一致
    environment:
      MYSQL_ROOT_PASSWORD: hh109
      MYSQL_DATABASE: HG_MLC_DB
    ports:
      - "3307:3306" # 不能是："3307:3306"，会出现 端口占用问题，TODO：后面可以研究下
    # volumes:
      # - mysql_data:/var/lib/mysql # 持久化数据（推荐）
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-phh109"]
      interval: 5s
      # timeout: 20s
      retries: 5
      # start_period: 30s

  migrate:
    image: migrate/migrate
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../../migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "mysql://root:hh109@tcp(mysql:3306)/HG_MLC_DB",
        "up",
      ]
  app:
    build:
      context: ../../ # Dockerfile文件路径
      dockerfile: Dockerfile # Dockerfile名称
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      SERVER_ENV: debug
      KAFKA_REQUIRED: "false"
    ports:
      - "8080:8080"
