# MySQL教程: https://www.runoob.com/mysql/mysql-administration.html
; mysql启动：sudo mysql.server start
; mysql关闭: mysql.server stop
; 进入mysql指令环境: sudo mysql -u root -p
; 查看数据库: show databases;
; 使用db_test数据库: use db_test;
; 查看已有数据表: show tables;
; 数据表结构信息: show columns from 表名;

# redis启动: redis-server

# gin端口占用解决:
; 查找占用 8080 端口的进程 PID: sudo lsof -i :8080
; 终止进程（例如 PID 为 1234）: sudo kill -9 1234


[database]
Type = mysql
User = root
Password = hh109
#HOST = 数据库IP:数据库端口号 (127.0.0.1:3306)
Host = 127.0.0.1:3306
Name = db_test #blog
TablePrefix = blog_
